### ISSUE TITLE
Don't log "updated" messages or create Events if the secret has not changed

### ISSUE THREAD

**Issue by rgooding** [digitalis-io/vals-operator#7]
Currently whenever we check a secret we log the message "Secret created or updated" and we write an Event to K8s even if the secret did not change. We should stop logging that message (possibly replaced with a "secret has not changed" message) and only create the Event if the secret was changed.

**Comment by digiserg** [comment]
@rgooding I would not expect this to happen as the function exists before the recording occurs if no changes to the secret.

https://github.com/digitalis-io/vals-operator/blob/master/controllers/valssecret_controller.go#L148

**Comment by rgooding** [comment]
This seems to be caused by the comparison operation above that at line 113, the Annotations and Labels never match so the secret is always considered to have changed
